site_name: mbake Docs
site_url: http://metabake.org
repo_url: http://metabake.org
pages:
   - Home: index.md

   - Tutorial 1 - Setup S3 and mount: t1.md
   - Tutorial 2 - Learn Templating/Pug: t2.md
   - Tutorial 3 - Read from Firestore: t3.md
   - Tutorial 4(Optional) - Apply Auth and Write Data: t4.md

   - Resources: res.md
   - Next Steps: next.md
   - About: about.md

theme: readthedocs
