site_name: mBake Docs
site_url: http://MetaBake.org
repo_url: http://MetaBake.org
pages:
   - Home: index.md

   - Cloud 2.0 Part 1/S3: cloud1.md
   - Gentle Intro: gent.md
   - Pug 1/Intro: pug1.md

   - Cloud 2.0 Part II/Firestore: cloud2.md
   - Pug 2/Dynamic Binding RO: pug2.md
   - CRUD with Auth: crud.md

   - Resources: res.md
   - Next Steps: next.md
   - About: about.md

theme: readthedocs
