site_name: mBake Docs
site_url: http://MetaBake.org
repo_url: http://MetaBake.org
pages:
   - Home: index.md

   - Cloud v2.0 part 1/S3: cloud1.md
   - Gentle Into/Mock-ups: mock.md
   - Pug (you know it already) 1/Intro: pug1.md

   - Cloud v2.0 part II/FireStore: cloud2.md
   - Pug 2/Dynamic Binding: pug2.md

   - Master/Detial: masterDetail.md

   - Resources: res.md
   - Next Steps: next.md
   - About: about.md

theme: readthedocs
