site_name: mbake Docs
site_url: http://metabake.org
repo_url: http://metabake.org
pages:
   - Home: index.md

   - Gentle Intro: gent.md
   - T1 Setup S3 and mount: cloud1.md
   - T2 Learn Pug: pug1.md
   - T3 Read from Firestore: pug2.md
   - T4 Apply Auth and Write Data: cloud2.md

   - Resources: res.md
   - Next Steps: next.md
   - About: about.md

theme: readthedocs
